plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.onevour.core'
version = '2.0.0.7'

java {
    sourceCompatibility = JavaVersion.VERSION_11
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/onevour/spring-commons")
            credentials {
                username = project.findProperty("user") ?: System.getenv("USERNAME")
                password = project.findProperty("token") ?: System.getenv("TOKEN")
            }
        }
    }
    publications {
        gpr(MavenPublication) {
            from(components.java)
        }
    }
}

dependencies {
    // springframework
    api "org.springframework:spring-context"
    api "org.springframework:spring-beans"
    api "org.springframework:spring-aop"
    api "org.springframework:spring-web"
    // springframework boot
    api "org.springframework.boot:spring-boot-autoconfigure"
    // aop
    api "com.fasterxml.jackson.core:jackson-databind"
    api "javax.validation:validation-api"
    api "org.aspectj:aspectjweaver"
    api "org.slf4j:slf4j-api"
    // commons min version
    constraints {
        api("joda-time:joda-time:2.12.5")
        api("commons-io:commons-io:2.14.0")
        api("org.apache.commons:commons-lang3:3.12.0")
        api("org.apache.httpcomponents:httpclient:4.5.13")
    }
    // commons
    api 'joda-time:joda-time'
    api 'commons-io:commons-io'
    api 'org.apache.commons:commons-lang3'
    api 'org.apache.httpcomponents:httpclient'

    compileOnly "javax.servlet:javax.servlet-api"
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

}

tasks.named('test') {
    useJUnitPlatform()
}

