common.exclude=module-info\
                                ,module-info\
                                ,aj.org\
                                ,antlr\
                                ,ch.qos\
                                ,com.sun\
                                ,com.zaxxer\
                                ,javax\
                                ,lombok\
                                ,net.bytebuddy\
                                ,com.fasterxml\
                                ,com.intelij\
                                ,org.aopalliance\
                                ,org.apache\
                                ,org.aspectj\
                                ,org.checkerframework\
                                ,org.hibernate\
                                ,org.jboss\
                                ,org.joda\
                                ,org.postgresql\
                                ,org.osgi\
                                ,org.slf4j\
                                ,org.springframework\
                                ,org.yaml\
                                ,org.junit\
                                ,org.assertj\
                                ,org.mockito\
                                ,org.etsi\
                                ,org.w3\
                                ,org.openxmlformats\
                                ,org.xerial\
                                ,com.microsoft\
                                ,com.jayway\
                                ,com.objectweb\
                                ,net.minidev\
                                ,worker.org

# exclude jpa
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration