# database
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_sdk_sample
spring.datasource.username=postgres
spring.datasource.password=postgres

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=INFO
logging.level.com.asliri.core=TRACE


pokemon.base=https://pokeapi.co/api/v2
pokemon.ditto=/pokemon/ditto